### PR TITLE
Feature/batch request

### PR DESCRIPTION
**Pull request by vzotov**
- Added batch request for member and invite requests
- Added batch request for getting/updating cards

@Glympse/web PTAL

### CODE REVIEW

**Comment by j5kay** [comment]
Haven't had time to debug, but we've been seeing service errors to the effect of `invalid_arguments` responses for some of the batched commands. Please review/verify.

**Comment by vzotov** [comment]
Fixed, PTAL

**Comment by j5kay** [comment]
LGTM

**Comment by marreka** [comment]
Hey folks. This repository is public (and I'm getting github alerts for it). My guess is it shouldn't be :)

**Pull request merged**
